version: '3'
services:
  # redis container will changed to AWS Elastic Cache
  # postgres container will changed to AWS Relational Database Service
  nginx:
    image: ahmadleoyudanto/docker-multi-container-nginx
    mem_limit: 128m
    hostname: api
    ports:
      - '80:80'
  server:
    image: ahmadleoyudanto/docker-multi-container-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: ahmadleoyudanto/docker-multi-container-client
    mem_limit: 128m
    hostname: client
  worker:
    image: ahmadleoyudanto/docker-multi-container-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT